name: designlab
channels:
  - defaults
  - conda-forge
  - pytorch
  - anaconda
dependencies:
  - blas=1.0
  - ca-certificates=2021.5.25
  - certifi=2021.5.30
  - faiss-cpu=1.7.1
  - intel-openmp=2021.2.0
  - libcxx=10.0.0
  - libfaiss=1.7.1
  - libffi=3.3
  - llvm-openmp=10.0.0
  - mkl=2021.2.0
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.2.1
  - ncurses=6.2
  - numpy-base=1.20.2
  - openssl=1.1.1k
  - pip=21.1.2
  - python=3.7.10
  - readline=8.1
  - setuptools=52.0.0
  - six=1.16.0
  - sqlite=3.36.0
  - tk=8.6.10
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - absl-py==0.13.0
    - alembic==1.6.5
    - antlr4-python3-runtime==4.8
    - appdirs==1.4.4
    - appnope==0.1.2
    - aspect-based-sentiment-analysis==2.0.2
    - astunparse==1.6.3
    - attrs==21.2.0
    - backcall==0.2.0
    - black==21.6b0
    - blis==0.4.1
    - boto3==1.17.103
    - botocore==1.20.103
    - cachetools==4.2.2
    - catalogue==2.0.4
    - cffi==1.14.5
    - chardet==4.0.0
    - click==7.1.2
    - cliff==3.8.0
    - cmaes==0.8.2
    - cmd2==2.1.1
    - colorama==0.4.4
    - colorlog==5.0.1
    - cymem==2.0.5
    - decorator==5.0.9
    - filelock==3.0.12
    - gast==0.3.3
    - google-api-core==1.30.0
    - google-auth==1.32.1
    - google-auth-oauthlib==0.4.4
    - google-cloud-core==1.7.1
    - google-cloud-storage==1.40.0
    - google-crc32c==1.1.2
    - google-pasta==0.2.0
    - google-resumable-media==1.3.1
    - googleapis-common-protos==1.53.0
    - greenlet==1.1.0
    - grpcio==1.38.1
    - h5py==2.10.0
    - hydra-core==1.1.0
    - idna==2.10
    - importlib-metadata==4.6.0
    - importlib-resources==5.2.0
    - iniconfig==1.1.1
    - ipython==7.25.0
    - ipython-genutils==0.2.0
    - jedi==0.18.0
    - jinja2==3.0.1
    - jmespath==0.10.0
    - joblib==1.0.1
    - keras-preprocessing==1.1.2
    - mako==1.1.4
    - markdown==3.3.4
    - markupsafe==2.0.1
    - matplotlib-inline==0.1.2
    - murmurhash==1.0.5
    - mypy-extensions==0.4.3
    - nltk==3.6.2
    - numpy==1.21.0
    - oauthlib==3.1.1
    - omegaconf==2.1.0
    - opt-einsum==3.3.0
    - optuna==2.8.0
    - orderedset==2.0.3
    - packaging==20.9
    - parso==0.8.2
    - pathspec==0.8.1
    - pathy==0.6.0
    - pbr==5.6.0
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - plac==1.1.3
    - pluggy==0.13.1
    - preshed==3.0.5
    - prettytable==2.1.0
    - prompt-toolkit==3.0.19
    - protobuf==3.17.3
    - ptyprocess==0.7.0
    - py==1.10.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.20
    - pydantic==1.7.4
    - pygments==2.9.0
    - pyparsing==2.4.7
    - pyperclip==1.8.2
    - pytest==6.2.4
    - python-dateutil==2.8.1
    - python-editor==1.0.4
    - pytz==2021.1
    - pyyaml==5.4.1
    - regex==2021.4.4
    - requests==2.25.1
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - s3transfer==0.4.2
    - sacremoses==0.0.45
    - scikit-learn==0.24.2
    - scipy==1.4.1
    - sentencepiece==0.1.96
    - smart-open==5.1.0
    - spacy==3.0.6
    - spacy-legacy==3.0.6
    - sqlalchemy==1.4.20
    - srsly==2.4.1
    - stevedore==3.3.0
    - tensorboard==2.2.2
    - tensorboard-plugin-wit==1.8.0
    - tensorflow==2.2.0
    - tensorflow-estimator==2.2.0
    - termcolor==1.1.0
    - testfixtures==6.17.1
    - thinc==8.0.7
    - threadpoolctl==2.1.0
    - tokenizers==0.5.0
    - toml==0.10.2
    - tqdm==4.61.1
    - traitlets==5.0.5
    - transformers==2.5.0
    - typed-ast==1.4.3
    - typer==0.3.2
    - typing-extensions==3.10.0.0
    - urllib3==1.26.6
    - wasabi==0.8.2
    - wcwidth==0.2.5
    - werkzeug==2.0.1
    - wrapt==1.12.1
    - zipp==3.4.1
